/**
 * @file Dither.h
 * @brief This file contains functions for generating and deallocating a Bayer matrix for ordered dithering.
 */

#ifndef DITHER_H
#define DITHER_H

#include <stdlib.h>
#include "Error.h"

/**
 * @brief Generates a Bayer matrix for ordered dithering.
 *
 * This function generates a Bayer matrix of size n x n. The generated matrix is used for ordered dithering.
 *
 * @param n The side length of the matrix. It should be a power of 2.
 * @return A new Bayer matrix of size n x n. Memory deallocation with Dfree_bayer_matrix is the caller's responsibility.
 */
size_t **Dgenerate_bayer_matrix(size_t n);

/**
 * @brief Deallocates memory used by a Bayer matrix.
 *
 * This function deallocates the memory used by a Bayer matrix that was generated by Dgenerate_bayer_matrix.
 *
 * @param matrix The Bayer matrix to be freed. It should be a valid pointer to a Bayer matrix generated by Dgenerate_bayer_matrix.
 */
void Dfree_bayer_matrix(size_t **matrix);

#endif